//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recipe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Recipe()
        {
            this.Meals = new HashSet<Meal>();
        }
    
        public int RecipeId { get; set; }
        public string Name { get; set; }
        public string Url { get; set; }
        public int Servings { get; set; }
        public decimal CaloriesTotal { get; set; }
        public decimal CaloriesPerServing { get; set; }
        public decimal FatTotal { get; set; }
        public decimal FatPerServing { get; set; }
        public decimal ProteinTotal { get; set; }
        public decimal ProteinPerServing { get; set; }
        public decimal NetCarbsTotal { get; set; }
        public decimal NetCarbsPerServing { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Meal> Meals { get; set; }
    }
}
