//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfile
    {
        public int UserProfileId { get; set; }
        public string AspNetUserId { get; set; }
        public int CaloricIntakePerDay { get; set; }
        public int FatPerDay { get; set; }
        public int ProteinPerDay { get; set; }
        public int NetCarbsPerDay { get; set; }
    }
}
